Attribute VB_Name = "EnumModule1"
Option Explicit

'The MIT License (MIT)
'
'Copyright (c) 2020 FORREST
' Mateusz Milewski mateusz.milewski@mpsa.com aka FORREST
'
'Permission is hereby granted, free of charge, to any person obtaining a copy
'of this software and associated documentation files (the "Software"), to deal
'in the Software without restriction, including without limitation the rights
'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
'copies of the Software, and to permit persons to whom the Software is
'furnished to do so, subject to the following conditions:
'
'The above copyright notice and this permission notice shall be included in all
'copies or substantial portions of the Software.
'
'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
'SOFTWARE.
'
'
' THE EVO TOOL



' only in EP
Public Enum E_CFG_SQ01_QUERY
    E_TYPE_DE_DOC_ACHAT = 29     ' 29
    E_CODE_DE_SUPP = 51
    E_NUMERO = 73
    E_DIV = 95
End Enum


Public Enum E_FILE_TYPE
    E_MASTER_PUS
    E_FEED_CPL
    E_TP04_01
    E_SQ01
    E_INTERROCOM
    E_MB51
End Enum


Public Enum E_FORM_SCENARIO_TYPE
    E_FORM_SCENARIO_COPY_PASTE = 1
    E_FORM_SCENARIO_CREATE_PIVOT_SCENARIO
    E_FORM_SCENARIO_KPI
    E_FORM_SCENATIO_PRICE_MATCHING_FOR_TP04
    E_FORM_SCENATIO_PRICE_MATCHING_FOR_SQ01
End Enum


Public Enum E_COPY_HANDLER_INIT
    E_COPY_HANDLER_COPY_ONE = 1
    E_COPY_HANDLER_BY_TMC_OPT
    E_COPY_HANDLER_FOR_PIVOT_CREATION
End Enum



Public Enum E_KPI_SRC
    E_KPI_SRC_REF = 1
    E_KPI_SRC_V_COFOR
    E_KPI_SRC_E_COFOR
    E_KPI_SRC_SUPPLIER_NAME
    E_KPI_SRC_DAP
    E_KPI_SRC_NO_DATA
    E_KPI_SRC_TYPE_DE_PIECE
    E_KPI_SRC_UA
    E_KPI_SRC_PLE
    E_KPI_SRC_GREEN
    E_KPI_SRC_BLUE
    E_KPI_SRC_YELLOW
End Enum








Public Enum E_SQ01_CONFIG
    E_SQ01_CONFIG_MAKE_ALL
    E_SQ01_CONFIG_START_FROM_PASTING_ALREADY_PREPARED_INPUT_LIST
End Enum

'TP04_01

Public Enum E_TP04_01
    E_TP04_01_DOMAINE = 1
    E_TP04_01_ARTICLE
    E_TP04_01_REPERE_UTI
    E_TP04_01_DOC_ACHAT
    E_TP04_01_POSTE
    E_TP04_01_TYPE
    E_TP04_01_DIV
    E_TP04_01_FOUR
    E_TP04_01_DATE_DEBUT
    E_TP04_01_DATE_FIN
    E_TP04_01_UNITE_DE_PRIX
    E_TP04_01_PRIX
    E_TP04_01_UNITE
    E_TP04_01_DEV
End Enum

Public Enum E_FROM_SQ01_QUASI_TP04
    E_FROM_SQ01_QUASI_TP04_DOMAIN = 1
    E_FROM_SQ01_QUASI_TP04_ARTICLE
    E_FROM_SQ01_QUASI_TP04_RU
    E_FROM_SQ01_QUASI_TP04_DOC_ACHAT
    E_FROM_SQ01_QUASI_TP04_POSTE
    E_FROM_SQ01_QUASI_TP04_TYPE
    E_FROM_SQ01_QUASI_TP04_DIV
    E_FROM_SQ01_QUASI_TP04_FOUR
    E_FROM_SQ01_QUASI_TP04_DATE_DEBUT
    E_FROM_SQ01_QUASI_TP04_DATE_FIN
    E_FROM_SQ01_QUASI_TP04_UNITE
    E_FROM_SQ01_QUASI_TP04_SUM
    E_FROM_SQ01_QUASI_TP04_UNITE2_EMPTY
    E_FROM_SQ01_QUASI_TP04_CURRENCY
    E_FROM_SQ01_QUASI_TP04_II_RATE_UNIT_VALUE
    E_FROM_SQ01_QUASI_TP04_II_RATE_TO_EUR
    E_FROM_SQ01_QUASI_TP04_II_RATE_CALCED_SUM
    
End Enum


Public Enum E_SQ01_PREDEF
    E_SQ01_PREDEF_SYSTEM
    E_SQ01_PREDEF_LIST1
    E_SQ01_PREDEF_STD1
    E_SQ01_PREDEF_LIST2
    E_SQ01_PREDEF_STD2
End Enum


Public Enum E_N_SUPPLIERS
    E_N_SUPPLIERS_COFOR = 1
    E_N_SUPPLIERS_PLT
    E_N_SUPPLIERS_TYPE
    E_N_SUPPLIERS_DESC
    E_N_SUPPLIERS_COCD
    E_N_SUPPLIERS_COMPANY
    E_N_SUPPLIERS_BU_ORDER
    E_N_SUPPLIERS_ONL_ORDER
    E_N_SUPPLIERS_CONT
    E_N_SUPPLIERS_DEL_SCHED
    E_N_SUPPLIERS_GA_C_RESP
    E_N_SUPPLIERS_GA_EXE_SECTOR
    E_N_SUPPLIERS_DGP_SGR
    E_N_SUPPLIERS_SIGAPP_SIGMA
    E_N_SUPPLIERS_PROTO_FLAG
    E_N_SUPPLIERS_PURCH_ORG
    E_N_SUPPLIERS_INT_EXT_VEN
End Enum



Public Enum E_ORDER_INTERROCOM
    INTERROCOM_article = 1
    INTERROCOM_GM
    INTERROCOM_Designation_achat
    INTERROCOM_Div
    INTERROCOM_Date_prix
    INTERROCOM_cofor
    INTERROCOM_Fournisseur
    INTERROCOM_GA
    INTERROCOM_Un
    INTERROCOM_s
    INTERROCOM_N_cde
    INTERROCOM_Type
    INTERROCOM_e
    INTERROCOM_prix
    INTERROCOM_Devise
    INTERROCOM_Base_de_prix
    INTERROCOM_Repartition
    INTERROCOM_N_DA
    INTERROCOM_Date_DA
    INTERROCOM_FNR_fab
    INTERROCOM_FNR_Exp
    INTERROCOM_N_poste
End Enum

Public Enum E_OUT_INTERROCOM
    E_OUT_INTERROCOM_A = 1
    E_OUT_INTERROCOM_COFOR
    E_OUT_INTERROCOM_DIV
    E_OUT_INTERROCOM_UN
    E_OUT_INTERROCOM_FINAL_PRIX
    E_OUT_INTERROCOM_REP
End Enum


Public Enum E_MB51_AUTO_DECISION_LAYOUT
    E_MB51_AUTO_DECISION_LAYOUT_0
    E_MB51_AUTO_DECISION_LAYOUT_NEW
    E_MB51_AUTO_DECISION_LAYOUT_PREV
End Enum




Public Enum E_ADJUSTED_SQ01
    E_ADJUSTED_SQ01_Reference = 1
    E_ADJUSTED_SQ01_designation
    E_ADJUSTED_SQ01_QUANTITE_T
    E_ADJUSTED_SQ01_QUANTITE_CONF
    E_ADJUSTED_SQ01_CW
    E_ADJUSTED_SQ01_COFOR
    E_ADJUSTED_SQ01_nomFournisseur
    E_ADJUSTED_SQ01_progLivraison
    E_ADJUSTED_SQ01_numero_contrat
    E_ADJUSTED_SQ01_Nom_appro
    E_ADJUSTED_SQ01_Tel_appro
    E_ADJUSTED_SQ01_mail_appro
    E_ADJUSTED_SQ01_Nom_contact_log
    E_ADJUSTED_SQ01_Tel_contact_log
    E_ADJUSTED_SQ01_mail_contact_log
    E_ADJUSTED_SQ01_TMC
    E_ADJUSTED_SQ01_PRE_SERIAL_PRICE_YPRS_contract
    E_ADJUSTED_SQ01_INITIAL_SERIAL_PRICE
    E_ADJUSTED_SQ01_RATE_PRE_SERIAL
    E_ADJUSTED_SQ01_OKNOK
    E_ADJUSTED_SQ01_WITH_INDEX
    E_ADJUSTED_SQ01_IS_INTERNAL
    E_ADJUSTED_SQ01_IS_IN_TANGO
    E_ADJUSTED_SQ01_TANGO_PCS_PRICE
    ' new one from 060
    E_ADJUSTED_SQ01_DOMAIN
    E_ADJUSTED_SQ01_RU
    E_ADJUSTED_SQ01_DIV
    ' 061
    E_ADJUSTED_SQ01_MANAGER_DA
    '092
    E_ADJUSTED_SQ01_MANAGER_FAMILY
    E_ADJUSTED_SQ01_MANAGER_GROUP
End Enum



Public Enum E_FINAL_TOUCH_RECEPTION
    E_FINAL_TOUCH_RECEPTION_Mag = 1
    E_FINAL_TOUCH_RECEPTION_Mvt
    E_FINAL_TOUCH_RECEPTION_Designation_article
    E_FINAL_TOUCH_RECEPTION_Qte_UAc
    E_FINAL_TOUCH_RECEPTION_UAc
    E_FINAL_TOUCH_RECEPTION_Montant_di
    E_FINAL_TOUCH_RECEPTION_Dev
    E_FINAL_TOUCH_RECEPTION_article
    E_FINAL_TOUCH_RECEPTION_Date_cpt
    E_FINAL_TOUCH_RECEPTION_Fourn
    E_FINAL_TOUCH_RECEPTION_Cde_achat
    E_FINAL_TOUCH_RECEPTION_prix_Sigapp
    E_FINAL_TOUCH_RECEPTION_prix_Tango
    E_FINAL_TOUCH_RECEPTION_Ecart
    E_FINAL_TOUCH_RECEPTION_RU
    E_FINAL_TOUCH_RECEPTION_prix_cible
    E_FINAL_TOUCH_RECEPTION_Sigapp
    E_FINAL_TOUCH_RECEPTION_GAP
    E_FINAL_TOUCH_RECEPTION_OKNOK
    E_FINAL_TOUCH_RECEPTION_Interne
    E_FINAL_TOUCH_RECEPTION_Sem
    E_FINAL_TOUCH_RECEPTION_Manager_DA
    E_FINAL_TOUCH_RECEPTION_FAMILY
    E_FINAL_TOUCH_RECEPTION_GROUP
End Enum


Public Enum E_GREEN_LIGHT
    E_GREEN_LIGHT_Reference = 1
    E_GREEN_LIGHT_designation
    E_GREEN_LIGHT_QUANTITE_theorique
    E_GREEN_LIGHT_QUANTITE_confirmee
    E_GREEN_LIGHT_ECHANCIER_ONL_semaine
    E_GREEN_LIGHT_cofor
    E_GREEN_LIGHT_NOM_fournisseur
    E_GREEN_LIGHT_prog_livraison
    E_GREEN_LIGHT_numero_contrat
    E_GREEN_LIGHT_NOM_appro
    E_GREEN_LIGHT_Tel_appro
    E_GREEN_LIGHT_mail_appro
    E_GREEN_LIGHT_Nom_contact_log
    E_GREEN_LIGHT_Tel_contact_log
    E_GREEN_LIGHT_mail_contact_log
    E_GREEN_LIGHT_tmc
    E_GREEN_LIGHT_PRE_SERIAL_PRICE_YPRS_contract
    E_GREEN_LIGHT_INITIAL_SERIAL_PRICE
    E_GREEN_LIGHT_RATE_PRE_SERIAL_div_INIT_PRICE
    E_GREEN_LIGHT_OKNOK
    E_GREEN_LIGHT_TANGO_PRICE
    E_GREEN_LIGHT_TANGO_RATE
    E_GREEN_LIGHT_TANGO_OKNOK
    E_GREEN_LIGHT_MANAGER
    E_GREEN_LIGHT_Spending_sigapp
    E_GREEN_LIGHT_Spending_Target
    E_GREEN_LIGHT_Gap
    E_GREEN_LIGHT_rate
    E_GREEN_LIGHT_IS_INTERNAL
    E_GREEN_LIGHT_WITH_INDEX
    E_GREEN_LIGHT_IS_IN_TANGO
    ' new data
    E_GREEN_LIGHT_DOMAIN
    E_GREEN_LIGHT_RU
    E_GREEN_LIGHT_DIV
    ' family and grou[
    E_GREEN_LIGHT_FAMILY
    E_GREEN_LIGHT_GROUP
End Enum



Public Enum E_RECEPTION_REPORT_STEP
    E_RECEPTION_REPORT_STEP_GET_DATA_FROM_MB51
    E_RECEPTION_REPORT_STEP_GET_INTERNAL_SUPPLIERS
    E_RECEPTION_REPORT_STEP_MATCH_WITH_INTERROCOM
    E_RECEPTION_REPORT_STEP_FINAL_TOUCH
End Enum

Public Enum E_GREEN_LIGHT_REPORT_STEP
    E_GREEN_LIGHT_REPORT_STEP_GET_SQ01
    E_GREEN_LIGHT_REPORT_STEP_CONCAT
    E_GREEN_LIGHT_REPORT_STEP_ADJUST
    E_GREEN_LIGHT_REPORT_STEP_GET_INTERNAL_SUPPLIERS
    E_GREEN_LIGHT_REPORT_MATCH_WITH_INTERROCOM
    E_GREEN_LIGHT_REPORT_FINAL_TOUCH
End Enum



Public Enum E_MANAGERS_DA
    E_MANAGERS_DA_ARTICLE = 1
    E_MANAGERS_DA_ACHETEUR
    E_MANAGERS_DA_RU
    E_MANAGERS_DA_FAMILY
    E_MANAGERS_DA_GROUP
End Enum


Public Enum E_ECHANCIER_ONL_semaine_SCENARIO
    E_ECHANCIER_ONL_semaine_SCENARIO_PU
    E_ECHANCIER_ONL_semaine_SCENARIO_DEL
End Enum


Public Enum E_PIVOT_STD
    E_PIVOT_ANGEL_STD
    E_PIVOT_CAROLINE_STD
End Enum



' modeless leaf section
'.Cells(3, 2).Value = "Mass € Internal part (out of perimeter price * 1)"
'.Cells(4, 2).Value = "Number of Internal parts"
'.Cells(5, 2).Value = "Mass € Reception without Tango price"
'.Cells(6, 2).Value = "% mass €  without Tango price"
'.Cells(7, 2).Value = "number ref without Tango price"
'.Cells(8, 2).Value = "rate  : Mass Sigapp pre-serial price / initial price (without Tango price)"
'
'.Cells(11, 2).Value = "Mass € Sigapp reception (With Tango price)"
'.Cells(12, 2).Value = "number ref with Tango price"
'.Cells(13, 2).Value = "Including number no price * 1"
'
'.Cells(15, 2).Value = "Mass € target Price * 1"
'.Cells(16, 2).Value = "rate  : Mass reception Sigapp price /target price * 1 (with Tango price)"
'.Cells(17, 2).Value = "Mass € gap Sigapp price / price *1"

' NEW NEW
'.Cells(19, 2).Value rate  : Mass reception Sigapp price /TARGET price * 1
'.Cells(20, 2).ValueREAL Mass € gap Sigapp price / price *1

Public Enum E_MODELESS_LEAF_ORDER
    E_MODELESS_LEAF_ORDER_DATE = 2
    E_MODELESS_LEAF_ORDER_MASS_EUR_INTERNAL = 3
    E_MODELESS_LEAF_ORDER_NUM_OF_INTERNAL = 4
    E_MODELESS_LEAF_ORDER_MASS_EUR_WO_TANGO
    E_MODELESS_LEAF_ORDER_PERC_MASS_EUR_WO_TANGO
    E_MODELESS_LEAF_ORDER_NUM_OF_WO_TANGO
    E_MODELESS_LEAF_ORDER_RATE_WO_TANGO
    E_MODELESS_LEAF_ORDER_EMPTY_1 ' WO TANGO TARGET PRICE BY INITIAL PRICE
    E_MODELESS_LEAF_ORDER_MASS_EUR_W_TANGO
    E_MODELESS_LEAF_ORDER_NUM_OF_W_TANGO
    E_MODELESS_LEAF_ORDER_NUM_OF_W_TANGO_NOK
    E_MODELESS_LEAF_ORDER_EMPTY_2
    E_MODELESS_LEAF_ORDER_MASS_EUR_TARGET_PRICE
    E_MODELESS_LEAF_ORDER_RATE
    E_MODELESS_LEAF_ORDER_MASS_EUR_GAP
    E_MODELESS_LEAF_ORDER_EMPTY_3
    E_MODELESS_LEAF_ORDER_RATE_FINAL
    E_MODELESS_LEAF_ORDER_MASS_EUR_GAP_FINAL
End Enum
